---
title: "Individual and Population Level Uncertainty Interact to Determine Performance of Outbreak Detection"
header-title: true
authors:
  - name: "Callum R.K. Arnold"
    affiliations:
      - ref: "PSU-Bio"
      - ref: "CIDD"
    corresponding: true
    email: "cfa5228@psu.edu"
  - name: "Alex C. Kong"
    affiliations:
      - ref: "Hopkins-IH"
  - name: "Amy K. Winter"
    affiliations:
      - ref: "UGA"
  - name: "William J. Moss"
    affiliations:
      - ref: "Hopkins-IH"
      - ref: "Hopkins-Epi"
  - name: "Bryan N. Patenaude"
    affiliations:
      - ref: "Hopkins-IH"
  - name: "Matthew J. Ferrari"
    affiliations:
      - ref: "PSU-Bio"
      - ref: "CIDD"
affiliations:
  - id: "PSU-Bio"
    address: "Department of Biology, Pennsylvania State University, University Park, PA, USA 16802"
  - id: "CIDD"
    address: "Center for Infectious Disease Dynamics, Pennsylvania State University, University Park, PA, USA 16802"
  - id: "Hopkins-IH"
    address: "Department of International Health, Johns Hopkins Bloomberg School of Public Health, Baltimore, MD, USA 21205"
  - id: "UGA"
    address: "Department of Epidemiology, College of Public Health, University of Georgia, Athens, GA, USA 30602"
  - id: "Hopkins-Epi"
    address: "Department of Epidemiology, Johns Hopkins Bloomberg School of Public Health, Baltimore, MD, USA 21205"
execute:
  cache: true
  echo: false
  warning: false
  message: false
# bibliography: /Users/cfa5228/Documents/Repos/OutbreakDetection/manuscript/OD.bib
bibliography: OD.bib
bibliographystyle: springer-vancouver
toc: false
format:
  generic-manuscript-typst:
    keep-typ: true
---

# Results

## Tables

::: {#tbl-optimal-thresholds-accuracy}

```{=typst}
#let accuracy = csv("optimal-thresholds_accuracy.csv")

#table(
  columns: 9,
    fill: (x, y) => {
      if y == 0 {gray}
      if y == 1 {gray}
    },
  [], table.cell(colspan: 2, align: center, "Test Characteristic"), table.cell(colspan: 6, align: center, "Testing Rate"),
  ..accuracy.flatten()
)
```

Mean outbreak detection accuracy of each testing scenario at their specific optimal thresholds, when the average noise incidence is 8 times higher than the average measles incidence. A) the noise structure is dynamical, and the seasonality is in-phase with the measles incidence. B) the noise structure is Poisson only.

:::

::: {#tbl-optimal-thresholds-unavoidable}

```{=typst}
#let optimal_thresholds = csv("optimal-thresholds_unavoidable-cases.csv")

#table(
  columns: 9,
    fill: (x, y) => {
      if y == 0 {gray}
      if y == 1 {gray}
    },
  [], table.cell(colspan: 2, align: center, "Test Characteristic"), table.cell(colspan: 6, align: center, "Testing Rate"),
  ..optimal_thresholds.flatten()
)
```

Mean unavoidable cases per annum of each testing scenario at their specific optimal thresholds, scaled up to Ghana’s 2022 population, when the average noise incidence is 8 times higher than the average measles incidence. A) the noise structure is dynamical, and the seasonality is in-phase with the measles incidence. B) the noise structure is Poisson only.

:::

::: {#tbl-optimal-thresholds-delays}

```{=typst}
#let optimal_thresholds = csv("optimal-thresholds_detection-delays.csv")

#table(
  columns: 9,
    fill: (x, y) => {
      if y == 0 {gray}
      if y == 1 {gray}
    },
  [], table.cell(colspan: 2, align: center, "Test Characteristic"), table.cell(colspan: 6, align: center, "Testing Rate"),
  ..optimal_thresholds.flatten()
)
```

Mean outbreak alert delay (days) of each testing scenario at their specific optimal thresholds, when the average noise incidence is 8 times higher than the average measles incidence. A) the noise structure is dynamical, and the seasonality is in-phase with the measles incidence. B) the noise structure is Poisson only.

:::


## Figures

```{julia plotting-setup}
#| echo: false
include("optimal-thresholds-loading.jl");
include(srcdir("makie-plotting-setup.jl"));
using OutbreakDetection: line_plot
alpha = 0.2
nbanks = 1
legend_rowsize = Makie.Relative(0.05);
clinical_hline = false
```

```{julia}
#| fig-cap: "The difference between the proportion of the time series in outbreak for outbreak detection systems under different testing rates and noise structures. The shaded bands illustrate the 80% central interval, and the solid/dashed lines represent the mean estimate. Solid lines represent tests with 0-day turnaround times, and dashed lines represent tests with result delays."
#| label: fig-outbreak-proportion
line_plot(
    optimal_threshold_characteristics;
    outcome = :proportion_timeseries_in_outbreak,
    ylabel = "Proportion of Time\nSeries In Outbreak",
    alpha = alpha,
    facet_fontsize = 18,
    labelsize = 20,
    show_x_facet_label = true,
    show_y_facet_label = false,
    ylims = (0.5, 0.25),
    force = true,
    save_plot = false,
    clinical_hline = clinical_hline,
    nbanks = nbanks,
    legend_rowsize = legend_rowsize,
)
```

```{julia}
#| fig-cap: "The alert durations of outbreak detection systems under different testing rates and noise structures. The shaded bands illustrate the 80% central interval, and the solid/dashed lines represent the mean estimate. Solid lines represent tests with 0-day turnaround times, and dashed lines represent tests with result delays."
#| label: fig-alert-duration
line_plot(
    optimal_threshold_characteristics;
    outcome = :alert_duration_vec,
    ylabel = "Alert Duration\n(Days)",
    alpha = alpha,
    facet_fontsize = 18,
    labelsize = 20,
    show_x_facet_label = true,
    show_y_facet_label = false,
    ylims = (0, 170),
    force = true,
    save_plot = false,
    clinical_hline = clinical_hline,
    nbanks = nbanks,
    legend_rowsize = legend_rowsize,
)
```

```{julia}
#| fig-cap: "The number of alerts of outbreak detection systems under different testing rates and noise structures. The shaded bands illustrate the 80% central interval, and the solid/dashed lines represent the mean estimate. Solid lines represent tests with 0-day turnaround times, and dashed lines represent tests with result delays."
#| label: fig-num-alerts
line_plot(
    optimal_threshold_characteristics;
    outcome = :nalerts,
    ylabel = "Number of Alerts",
    alpha = alpha,
    facet_fontsize = 18,
    labelsize = 20,
    show_x_facet_label = true,
    show_y_facet_label = false,
    ylims = (0, 350),
    force = true,
    save_plot = false,
    clinical_hline = clinical_hline,
    nbanks = nbanks,
    legend_rowsize = legend_rowsize,
)
```



