---
title: "RDT - Gold Standard Equivalence"
author: "Callum Arnold"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    number_sections: FALSE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.dim = c(10, 8), fig.align = "center")
```

# Initial Look {.tabset .tabset-pills}

```{r, message=FALSE, warning=FALSE}
library(tidyverse)
library(janitor)
library(hrbrthemes)
library(kableExtra)
library(lubridate)
library(purrr)
library(glue)
library(MetBrewer)
```

```{r}
theme_set(theme_minimal())
```

```{r}
sens_range <- seq(0, 1, 0.05)
spec_range <- seq(0, 1, 0.05)
data <- tidyr::crossing(sens_range, spec_range)
```

```{r}
prev <- 0.05
tot <- 100

dis_pos <- tot * prev
dis_neg <- tot * (1 - prev)
```

```{r}
test <- map2_dfr(
  .x = data$sens_range,
  .y = data$spec_range,
  .f = function(.x, .y){
    true_pos <- dis_pos * .x
    true_neg <- dis_neg * .y
    false_pos <- dis_neg * (1 - .y)
    false_neg <- dis_pos * (1 - .x)

    test_pos <- true_pos + false_pos
    test_neg <- true_neg + false_neg

    ppv <- true_pos / test_pos
    npv <- true_neg / test_neg

    tibble(
      sens = .x,
      spec = .y,
      true_pos = true_pos,
      true_neg = true_neg,
      false_pos = false_pos,
      false_neg = false_neg,
      test_pos = test_pos,
      test_neg = test_neg,
      ppv = ppv,
      npv = npv
    )
  }
)
```

```{r}
ggplot(test, aes(x = sens, y = spec, z = test_pos)) +
  geom_contour_filled() +
  scale_fill_manual(values = met.brewer("OKeeffe2", 10)) +
  labs(
    title = "Number of Positive Tests by Sensitivity and Specificity",
    subtitle = glue("Prevalence = {prev}, Total Tests = {tot}, Disease Positives = {dis_pos}"),
    x = "Sensitivity",
    y = "Specificity",
    fill = "Number of Positive Tests"
  ) +
  theme(legend.position = "bottom")
```

```{r}
ggplot(test, aes(x = sens, y = spec, z = ppv)) +
  geom_contour_filled() +
  scale_fill_manual(values = met.brewer("Hokusai2", 10)) +
  labs(
    title = "PPV by Sensitivity and Specificity",
    subtitle = glue("Prevalence = {prev}, Total Tests = {tot}, Disease Positives = {dis_pos}"),
    x = "Sensitivity",
    y = "Specificity",
    fill = "PPV"
  ) +
  theme(legend.position = "bottom")
```