name = "OutbreakDetectionUtils"
uuid = "f998a708-2341-46f4-85c5-02aab2fba5ed"
authors = ["Callum Arnold <24391445+arnold-c@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
FromFile = "ff7dd447-1dcb-4ce3-b8ac-22a812192de7"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "1.6.7"
