CLINICAL_CASE_TEST_SPEC = IndividualTestSpecification(1.0, 0.0, 0)
EPI_LINKED_CASE_TEST_SPEC = IndividualTestSpecification(1.0, 0.8, 0)
CLINICAL_TEST_SPECS = (CLINICAL_CASE_TEST_SPEC, EPI_LINKED_CASE_TEST_SPEC)
