const CLINICAL_CASE_TEST_SPEC = IndividualTestSpecification(1.0, 0.0, 0)
const EPI_LINKED_CASE_TEST_SPEC = IndividualTestSpecification(1.0, 0.8, 0)
const CLINICAL_TEST_SPECS = (CLINICAL_CASE_TEST_SPEC, EPI_LINKED_CASE_TEST_SPEC)
